### PR TITLE
Clickable phone numbers

### LINKED ISSUE #161: Make phone number clickable throughout site
> Our SEO/SEM people asked if we could get some of the phone numbers clickable on the mobile. I looked through and found that most everything that is included in regular copy on the page - the phone numbers are hot. We noticed thought that anything that’s included dynamically (like the Lodging Properties, Dining, Equipment Rental, Tour Guide & Charters, Events and Calendar) are not hot. 

> Is there a way to make these listings have hot phone numbers? My SEO team suggested just adding an <a href> but I’m not sure that is best practice. Either way - it would help us track people calling the businesses from the website directly.

### PR DESCRIPTION
**Pull request by AdamChlan**
Fixes #161

### CODE REVIEW

**Comment by AdamChlan** [comment]
@regisphilibert I have this started here, on the Lodging area only:

https://deploy-preview-162--oregonsadventurecoast.netlify.app/lodging/

I'm curious on your thoughts on how this should be handled on desktop. At the moment the phone numbers are taking on the style of a hyperlink - red and underlined - on desktop. I can remove that style if you think that's best. I suppose people are not typically using their desktop computer to initiate calls. Or maybe you have handled this differently in other projects?

**Review by regisphilibert — CHANGES_REQUESTED** [review]
The client mentioned (issue desc) other locations on the site. Dining etc... I think most of those are in the JS. But we have a js file for each "cards type" So you might need to apply to all files. 

What I suggest you do is create a function in `src/js/common/` to be imported it in the files. The function would take one parameter, the phone number, and turn it into a link.
Then you can simply use the function wherever needed in the JS files.

**Comment by regisphilibert** [comment]
I missed your last comment, do did not see this as WIP sorry about that.

**Comment by regisphilibert** [comment]
> I'm curious on your thoughts on how this should be handled on desktop. At the moment the phone numbers are taking on the style of a hyperlink - red and underlined - on desktop. I can remove that style if you think that's best. I suppose people are not typically using their desktop computer to initiate calls. Or maybe you have handled this differently in other projects?

Well... as I recalled iOS used to handle this... turning phone numbers into links... There is a `meta` tag you can add to your site to prevent the behaviour but it's not on this site so not quiet sure why iOS is not doing it...

In any case, if you follow my recommendation above to create a function to handle the links, we'll be able to add a class which will apply the styling only when needed. (Based on screen width or other media query targeting phones)

**Review by regisphilibert — APPROVED** [review]

**Comment by AdamChlan** [comment]
@regisphilibert I have this updated in the Lodging area - https://deploy-preview-162--oregonsadventurecoast.netlify.app/lodging/

I created a function, and have applied it following the lead established on that template. I can get this moved throughout the rest of the templates if this look good to you.

**Comment by regisphilibert** [comment]
Thanks @AdamChlan you can go ahead and apply to the rest of the pages.

**Comment by AdamChlan** [comment]
@regisphilibert  Here are links to see this in action:

Lodging: https://deploy-preview-162--oregonsadventurecoast.netlify.app/lodging/
Calendar: https://deploy-preview-162--oregonsadventurecoast.netlify.app/calendar/ - need to scroll down to Villa Antinori event.
Equipment Rental - https://deploy-preview-162--oregonsadventurecoast.netlify.app/equipment-rent-and-buy/
Tour Guides & Charters - https://deploy-preview-162--oregonsadventurecoast.netlify.app/tour-guides-and-charters/
Dining - https://deploy-preview-162--oregonsadventurecoast.netlify.app/dining/

Events are not active so we can't confirm there, but the code is in place.

**Pull request merged**
