### PR TITLE
Add CTAs to Regular Pages

### LINKED ISSUE #220: Create a documents shortcode to include PDFs CTA in body
Dining-Page-Header-Changes-04-22

First use will be on dining page following these details:
[Dining-Page-Details.pdf](https://github.com/theNewDynamic/oregonsadventurecoast.com/files/8464610/Dining-Page-Details.pdf)

### PR DESCRIPTION
**Pull request by regisphilibert**
- [x] shortcode logic
- [x] styling
- [x] CMS

Fixes #220

### CODE REVIEW

**Comment by regisphilibert** [comment]
@AdamChlan I wonder if we can find a solution to constraint the height of the image maybe using a simple sensible max-height. But I'm not sure of the consequences, we can chat if needed. Thanks!

**Comment by AdamChlan** [comment]
@regisphilibert I set a width on the image, so I'm not sure setting a max height will work. Thinking it would force the image out of proportion. Is the goal to get all the images the same size? Maybe a transform can be used, where we crop if needed?

**Comment by regisphilibert** [comment]
We can chat at standup, but I think removing the width and setting a max-height (~100px) might work. Of course if they use a landscape picture, it would look weird but they're not doing it yet...

**Comment by AdamChlan** [comment]
@regisphilibert I have the max width and max height in place as discussed.

**Pull request merged**
